server:
  port: 3000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Sid12
    url: jdbc:mysql://localhost:3306/dev
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
